### ISSUE TITLE
Is it possible to interpret this read structure I have ?

### ISSUE THREAD

**Issue by callumparr** [yachielab/Interstellar#3]
![primers](https://user-images.githubusercontent.com/41637575/168215057-78af05d0-2375-404e-8080-5d3ba17d3d65.png)

I want to deduplicate my data off the long-read ONT platform using the following read structure. The closest tool I can find is handling 10x libraries on long-read platforms but in that case, they have a defined structure at one end of the read to look out for. In my case, I want to be able to use both the 5' and 3' UMI in combination.

**Comment by kijiy** [comment]
Hi, a regular expression pattern like 
^(?P<fwd>CTACT...)(?P<UMI5>.{25})(?P<linker5>GTGG...)(?P<cDNA>.+)(?P<constant3>GCATC)(?P<UMI3>.{15})(?P<rev>GGCT...).*$
should be able to extract your sequence segments. This website (https://regex101.com/) is useful for testing the regular expression pattern (specify 'python'). In addition to the default python regular expression, you can use 'fuzzy matching' regular expression patterns to allow constant sequences to have mismatches/indels. 

Note that it might take time to process long-read sequences.

**Comment by callumparr** [comment]
Sorry I am not familar with such pattern recognition:

I tried the pattern you recommened at the website and it gives error 


```

"^(?PCTACT...)(?P.{25})(?PGTGG...)(?P.+)(?PGCATC)(?P.{15})(?PGGCT...).*$"gm

All the errors detected are listed below, from left to right, as they appear in the pattern.
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
(? Incomplete group structure
) Incomplete group structure
```

**Comment by kijiy** [comment]
I'm sorry, it seems the group name had disappeared.

This is the correct regex pattern, but the exact same pattern wouldn't work since I didn't write down all the fwd/linker/rev sequences.
`^(?P<fwd>CTACT[rest of the fwd sequence])(?P<umi1>.{25})(?P<linker5>GTGG[rest of the linker sequence])(?P<DNA>.+)(?P<constant>GCATC)(?P<umi2>.{15})(?P<rev>GGCT[rest of the rev sequence]).*$`

Replace the [rest of ...] block with the correct sequence. I would recommend you first play around with regular expressions on the website I shared above! I hope it helps.
